version: "3"
services:
  rest_api:
    build:
      context: .
    depends_on: [
      postgres
    ]
    ports:
      - "8000:8000"
    links:
      - postgres:psqldb
    networks:
      - webnet
  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    networks:
      - webnet
networks:
  webnet: